export const state = false;

export const search_terms = [
    "Follow the innate feelings inside of you",
    "life keeps getting better",
    "contact that person and tell them",
    "question everything",
    "free thinking",
    "style is genderless",
    "never a master",
    "no longer have a manager",
    "feels weird at first",
    "pick up a hammer",
    "universe will assist you",
    "protect your ability to create",
    "respect people for being themselves",
    "victimization",
    "distraction is the enemy of vision",
    "hard-core capitalist",
    "you have the best ideas",
    "fresh air is healing",
    "emoji next to",
    "past the past",
    "life stems from either",
    "all you have to be is",
    "just stop lying about",
    "trust your feelings",
    "sometimes you have to get rid of everything",
    "playing chess with life",
    "sometimes we all need hugs",
    "their own biggest fan",
    "constantly birnging up the past",
    "be still and enjoy your own imagination",
    "be in the moment",
    "authenticity for approval",
    "naps are awesome",
    "the true character of a person watch",
    "consciousness"
]